site_title = "MyArxiv"
limit_days = 7
cache_url = "https://qinyu-allen-zhao.github.io/MyArxiv/cache.json"

[[sources]]
limit = 300
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 300
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
